<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>嘿市 - 分享快乐 愉悦他人</title>
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <style type="text/css">

        a{
            text-decoration: none;
        }

    </style>
</head>
<body>
<nav class="shelf">
    <a href="/#/home" class="book home-page">&nbsp;&nbsp;主&nbsp;&nbsp;&nbsp;&nbsp;页</a>
    <a href="/#/about" class="book about-us">&nbsp;&nbsp;关于我们</a>
    <a class="book contact">&nbsp;&nbsp;加入我们</a>
    <a href="mailto: shangwu@iwowcn.com" class="book faq">&nbsp;&nbsp;商务合作</a>
    <span class="book not-found"></span>

    <span class="door left"></span>
    <span class="door right"></span>
</nav>
<h1>Error 404</h1>
<p>糟糕，您要找页面被吃了。。。</p>

</body>
</html>